### PR TITLE
CLOUD-220 Optimize login and registration process

### PR DESCRIPTION
**Pull request by aba-langenegger**
- Add feature specific translations in en/fr/it
 - Use larger buttons
 - Expand language switch only if click/tap on it, not on hover

### CODE REVIEW

**Comment by aba-langenegger** [comment]
@hug-abacus can you please review this today so it can be released to DEV in timely manner for the Abacus Conference

**Review by ghost — COMMENTED** [review]
/lgtm

**Comment by aba-langenegger** [comment]
Checked on on DEV instance. Looks OK.

**Pull request merged**
